//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceAim3D.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpaceAim3D.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please calibrate the compass and press the back button..
        /// </summary>
        public static string CalibrationInformation {
            get {
                return ResourceManager.GetString("CalibrationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS receiver is disabled.
        /// </summary>
        public static string GeolocatorDisabled {
            get {
                return ResourceManager.GetString("GeolocatorDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing GPS receiver....
        /// </summary>
        public static string GeolocatorInitializing {
            get {
                return ResourceManager.GetString("GeolocatorInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading GPS location....
        /// </summary>
        public static string GeolocatorNoData {
            get {
                return ResourceManager.GetString("GeolocatorNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS receiver is not available.
        /// </summary>
        public static string GeolocatorNotAvailable {
            get {
                return ResourceManager.GetString("GeolocatorNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author: Marcin Jamro.
        /// </summary>
        public static string HelpAuthor {
            get {
                return ResourceManager.GetString("HelpAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy the game! :-).
        /// </summary>
        public static string HelpEnjoy {
            get {
                return ResourceManager.GetString("HelpEnjoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook profile.
        /// </summary>
        public static string HelpFacebookProfile {
            get {
                return ResourceManager.GetString("HelpFacebookProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game aim is to steer the space rocket to achieve the target planet and avoid asteroids. After reaching the aim, the game level and difficulty increase. Every crash breaks the rocket. The game ends when the player runs out of rockets..
        /// </summary>
        public static string HelpGameAim {
            get {
                return ResourceManager.GetString("HelpGameAim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game website.
        /// </summary>
        public static string HelpGameWebsite {
            get {
                return ResourceManager.GetString("HelpGameWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string HelpGroupAbout {
            get {
                return ResourceManager.GetString("HelpGroupAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game aim.
        /// </summary>
        public static string HelpGroupGameAim {
            get {
                return ResourceManager.GetString("HelpGroupGameAim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steering.
        /// </summary>
        public static string HelpGroupSteering {
            get {
                return ResourceManager.GetString("HelpGroupSteering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpHeader {
            get {
                return ResourceManager.GetString("HelpHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More information:.
        /// </summary>
        public static string HelpMoreInformation {
            get {
                return ResourceManager.GetString("HelpMoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Aim 3D.
        /// </summary>
        public static string HelpName {
            get {
                return ResourceManager.GetString("HelpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send e-mail.
        /// </summary>
        public static string HelpSendEmail {
            get {
                return ResourceManager.GetString("HelpSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should rotate the phone to indicate a correct direction of the rocket..
        /// </summary>
        public static string HelpSteering {
            get {
                return ResourceManager.GetString("HelpSteering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 0.0.0.1.
        /// </summary>
        public static string HelpVersion {
            get {
                return ResourceManager.GetString("HelpVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot download players data!.
        /// </summary>
        public static string MapCannotDownloadData {
            get {
                return ResourceManager.GetString("MapCannotDownloadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading players data....
        /// </summary>
        public static string MapDownloadingData {
            get {
                return ResourceManager.GetString("MapDownloadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players map.
        /// </summary>
        public static string MapHeader {
            get {
                return ResourceManager.GetString("MapHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate.
        /// </summary>
        public static string MapNavigate {
            get {
                return ResourceManager.GetString("MapNavigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string MenuMap {
            get {
                return ResourceManager.GetString("MenuMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play!.
        /// </summary>
        public static string MenuPlay {
            get {
                return ResourceManager.GetString("MenuPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranks.
        /// </summary>
        public static string MenuRanks {
            get {
                return ResourceManager.GetString("MenuRanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;play&apos;, &apos;map&apos;, &apos;world&apos;, &apos;ranks&apos;, &apos;settings&apos;, &apos;web&apos;, or &apos;help&apos;.
        /// </summary>
        public static string MenuSpeechAnswerExample {
            get {
                return ResourceManager.GetString("MenuSpeechAnswerExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should enable the speech recognition to use the voice mechanism in the game..
        /// </summary>
        public static string MenuSpeechErrorMessage {
            get {
                return ResourceManager.GetString("MenuSpeechErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice mechanism.
        /// </summary>
        public static string MenuSpeechErrorTitle {
            get {
                return ResourceManager.GetString("MenuSpeechErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigating to the {0} screen.
        /// </summary>
        public static string MenuSpeechNavigatingMessage {
            get {
                return ResourceManager.GetString("MenuSpeechNavigatingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which part do you want to launch?.
        /// </summary>
        public static string MenuSpeechQuestion {
            get {
                return ResourceManager.GetString("MenuSpeechQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string MenuWeb {
            get {
                return ResourceManager.GetString("MenuWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World.
        /// </summary>
        public static string MenuWorld {
            get {
                return ResourceManager.GetString("MenuWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot download results! Please check your internet connection..
        /// </summary>
        public static string RanksCannotDownloadResults {
            get {
                return ResourceManager.GetString("RanksCannotDownloadResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading results....
        /// </summary>
        public static string RanksDownloadingResults {
            get {
                return ResourceManager.GetString("RanksDownloadingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranks.
        /// </summary>
        public static string RanksHeader {
            get {
                return ResourceManager.GetString("RanksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 24h.
        /// </summary>
        public static string RanksLast24h {
            get {
                return ResourceManager.GetString("RanksLast24h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string RanksLocal {
            get {
                return ResourceManager.GetString("RanksLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall.
        /// </summary>
        public static string RanksOverall {
            get {
                return ResourceManager.GetString("RanksOverall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string SettingsGroupGame {
            get {
                return ResourceManager.GetString("SettingsGroupGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string SettingsGroupUser {
            get {
                return ResourceManager.GetString("SettingsGroupUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsHeader {
            get {
                return ResourceManager.GetString("SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music volume:.
        /// </summary>
        public static string SettingsMusicVolume {
            get {
                return ResourceManager.GetString("SettingsMusicVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string SettingsName {
            get {
                return ResourceManager.GetString("SettingsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Name&quot; setting can be presented to anyone with game results and location data. It can be also changed later..
        /// </summary>
        public static string SettingsNameDescription {
            get {
                return ResourceManager.GetString("SettingsNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name can contain only capital (A-Z) and small (a-z) letters, digits (0-9), &quot;-&quot;, and &quot;_&quot; chars. Its length has to be greater or equal to 3 and less or equal to 10..
        /// </summary>
        public static string SettingsNameIncorrectMessage {
            get {
                return ResourceManager.GetString("SettingsNameIncorrectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect name!.
        /// </summary>
        public static string SettingsNameIncorrectTitle {
            get {
                return ResourceManager.GetString("SettingsNameIncorrectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string SettingsPrivacy {
            get {
                return ResourceManager.GetString("SettingsPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Space Aim 3D privacy policy is available on the following website:.
        /// </summary>
        public static string SettingsPrivacyDescription {
            get {
                return ResourceManager.GetString("SettingsPrivacyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send location:.
        /// </summary>
        public static string SettingsSendLocation {
            get {
                return ResourceManager.GetString("SettingsSendLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If &quot;Send location&quot; option is enabled, your current location is automatically sent over the Internet and can be presented to anyone in the game..
        /// </summary>
        public static string SettingsSendLocationDescription {
            get {
                return ResourceManager.GetString("SettingsSendLocationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibrations:.
        /// </summary>
        public static string SettingsVibrations {
            get {
                return ResourceManager.GetString("SettingsVibrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot post the message at your wall! Such a situation can occur if you have recently posted the message from Space Aim 3D..
        /// </summary>
        public static string WebFbMessageFailure {
            get {
                return ResourceManager.GetString("WebFbMessageFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message has been posted at your wall! Thank you!.
        /// </summary>
        public static string WebFbMessageSuccess {
            get {
                return ResourceManager.GetString("WebFbMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook post.
        /// </summary>
        public static string WebFbMessageTitle {
            get {
                return ResourceManager.GetString("WebFbMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am playing the Space Aim 3D game! Do you know it? :-).
        /// </summary>
        public static string WebFbPost {
            get {
                return ResourceManager.GetString("WebFbPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest news.
        /// </summary>
        public static string WebGroupNews {
            get {
                return ResourceManager.GetString("WebGroupNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string WebGroupRate {
            get {
                return ResourceManager.GetString("WebGroupRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook &amp; Twitter.
        /// </summary>
        public static string WebGroupSocial {
            get {
                return ResourceManager.GetString("WebGroupSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string WebHeader {
            get {
                return ResourceManager.GetString("WebHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot download the latest news about the Space Aim 3D game..
        /// </summary>
        public static string WebLatestNewsErrorMessage {
            get {
                return ResourceManager.GetString("WebLatestNewsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string WebLatestNewsErrorTitle {
            get {
                return ResourceManager.GetString("WebLatestNewsErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project website.
        /// </summary>
        public static string WebProjectWebsite {
            get {
                return ResourceManager.GetString("WebProjectWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish at Facebook wall.
        /// </summary>
        public static string WebPublish {
            get {
                return ResourceManager.GetString("WebPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Space Aim 3D.
        /// </summary>
        public static string WebRate {
            get {
                return ResourceManager.GetString("WebRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweet at Twitter.
        /// </summary>
        public static string WebTweet {
            get {
                return ResourceManager.GetString("WebTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred! Please try again..
        /// </summary>
        public static string WebTwError {
            get {
                return ResourceManager.GetString("WebTwError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered the incorrect PIN!.
        /// </summary>
        public static string WebTwIncorrectPIN {
            get {
                return ResourceManager.GetString("WebTwIncorrectPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To authorize the game to publish an update, you should type username and password to the Twitter account, press &quot;Authorize app&quot; button, type the PIN in the field below, and press &quot;Go&quot;!.
        /// </summary>
        public static string WebTwInstruction {
            get {
                return ResourceManager.GetString("WebTwInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot tweet! Such a situation can occur if you have recently updated your status from Space Aim 3D..
        /// </summary>
        public static string WebTwMessageFailure {
            get {
                return ResourceManager.GetString("WebTwMessageFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tweet has been published! Thank you!.
        /// </summary>
        public static string WebTwMessageSuccess {
            get {
                return ResourceManager.GetString("WebTwMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter update.
        /// </summary>
        public static string WebTwMessageTitle {
            get {
                return ResourceManager.GetString("WebTwMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am playing the @SpaceAim3D game! Do you know it? :-).
        /// </summary>
        public static string WebTwStatus {
            get {
                return ResourceManager.GetString("WebTwStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please calibrate the compass!.
        /// </summary>
        public static string WorldCalibrateCompass {
            get {
                return ResourceManager.GetString("WorldCalibrateCompass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot download players data!.
        /// </summary>
        public static string WorldCannotDownloadData {
            get {
                return ResourceManager.GetString("WorldCannotDownloadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start the augmented reality feature!.
        /// </summary>
        public static string WorldCannotStartAR {
            get {
                return ResourceManager.GetString("WorldCannotStartAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players world.
        /// </summary>
        public static string WorldHeader {
            get {
                return ResourceManager.GetString("WorldHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string WorldLoadingMessage1 {
            get {
                return ResourceManager.GetString("WorldLoadingMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading the augmented reality feature!.
        /// </summary>
        public static string WorldLoadingMessage2 {
            get {
                return ResourceManager.GetString("WorldLoadingMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate.
        /// </summary>
        public static string WorldNavigate {
            get {
                return ResourceManager.GetString("WorldNavigate", resourceCulture);
            }
        }
    }
}
