<?xml version="1.0" encoding="utf-8"?><Database Name="Db" Class="DbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Db.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Players" Member="Players">
    <Type Name="Player">
      <Column Name="PlayerId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[Key]" Member="Key" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LocationLatitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LocationLongitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Player_Result" Member="Results" ThisKey="PlayerId" OtherKey="PlayerId" Type="Result" />
    </Type>
  </Table>
  <Table Name="dbo.Results" Member="Results">
    <Type Name="Result">
      <Column Name="ResultId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Score" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PlayerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Player_Result" Member="Player" ThisKey="PlayerId" OtherKey="PlayerId" Type="Player" IsForeignKey="true" />
    </Type>
  </Table>
</Database>